In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

# Scrapping Page 1<br>
 We will use this code to generalize, and scrap from multiple pages.

In [9]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1', headers = headers).text

In [10]:
soup = BeautifulSoup(webpage, 'lxml')
companies = soup.find_all('div', class_ = "companyCardWrapper")

In [11]:
# On page 1
#Features
name = []
rating = []
reviews_K = []
highly_rated = []
ctype = []
hq = []
no_of_employees= []
desc = []



for company in companies:
    name.append(company.find('h2').text.strip())
    rating.append(float(company.find('span', class_ = "companyCardWrapper__companyRatingValue").text.strip()))
    reviews_K.append(float(company.find('span', class_ ="companyCardWrapper__ActionCount").text.strip()[:-1]))
    highly_rated.append(company.find('span', class_ = "companyCardWrapper__ratingValues").text.strip())
    hq.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[-1].split("+")[0])
    ctype.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[0])
    no_of_employees.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[1][:-10])

    company_url = "https://www.ambitionbox.com/overview/{}-overview".format(company.find('h2').text.strip())
    webpage_desc = requests.get(company_url, headers = headers).text
    soup_desc = BeautifulSoup(webpage_desc, 'lxml')
    #desc.append(soup_desc.find('div', class_="description mt-12").text)
    try:
      desc.append(soup_desc.find('div', class_="description mt-12").text)
    except:
      desc.append(np.nan)

In [12]:
# Checking how much data is scraped
dictionary_pg1 ={'name': name, 'rating': rating, 'ctype': ctype, 'highly_rated': highly_rated, 'hq':hq, 'no_of_employees': no_of_employees,'reviews_K':reviews_K ,'desc': desc}
#df_pg1 = pd.DataFrame(dictionary_pg1)
vals = [len(val) for val in dictionary_pg1.values()]
print(vals)

[20, 20, 20, 20, 20, 20, 20, 20]

So, There are 20 company per page. Let's convert it to a pandas dataframe.

In [13]:
page_1_dict = {'name': name, 'rating': rating, 'ctype': ctype, 'highly_rated': highly_rated, 'hq':hq,'reviews_K':reviews_K, 'no_of_employees': no_of_employees,'desc': desc}

df_page_1 = pd.DataFrame(page_1_dict)
df_page_1 = df_page_1[["name", "rating","ctype", "highly_rated","hq", "reviews_K", "no_of_employees",  "desc" ]]

In [14]:
# Checking Data From First Page
df_page_1

,name,rating,ctype,highly_rated,hq,reviews_K,no_of_employees,desc
0,TCS,3.8,IT Services & Consulting,"Job Security, Work Life Balance",Mumbai,74.5,1 Lakh+,"Tata Consultancy Services is an IT services, c..."
1,Accenture,4.0,IT Services & Consulting,"Company Culture, Skill Development / Learning,...",Dublin,47.2,1 Lakh+,Accenture is a global professional services co...
2,Cognizant,3.9,IT Services & Consulting,Skill Development / Learning,Teaneck. New Jersey.,42.6,1 Lakh+,"At Cognizant, we give organizations the insigh..."
3,Wipro,3.8,IT Services & Consulting,Job Security,Bangalore/Bengaluru,40.1,1 Lakh+,"Wipro Limited (NYSE: WIT, BSE: 507685, NSE: WI..."
4,Capgemini,3.9,IT Services & Consulting,"Job Security, Work Life Balance, Skill Develop...",Paris,34.6,1 Lakh+,Capgemini is a global business and technology ...
5,HDFC Bank,4.0,Banking,"Job Security, Skill Development / Learning",Mumbai,34.4,1 Lakh+,The Housing Development Finance Corporation Li...
6,ICICI Bank,4.0,Banking,"Job Security, Skill Development / Learning, Co...",Mumbai,34.1,1 Lakh+,The Bank continue to achieve profitable growth...
7,Infosys,3.8,IT Services & Consulting,"Job Security, Company Culture, Skill Developme...",Bengaluru/Bangalore,32.4,1 Lakh+,Infosys is a global leader in next-generation ...
8,HCLTech,3.7,IT Services & Consulting,Job Security,Noida,29.1,1 Lakh+,"HCLTech is a global technology company, home t..."
9,Tech Mahindra,3.7,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits",Pune,28.1,1 Lakh+,Tech Mahindra offers innovative and customer-c...
10,Genpact,3.9,IT Services & Consulting,"Job Security, Skill Development / Learning, Wo...",New York,26.6,1 Lakh+,Genpact (NYSE: G) is a global professional ser...
11,Axis Bank,3.9,Banking,Job Security,Mumbai,22.4,50k-1 Lakh,Axis Bank is the third largest private sector ...
12,Teleperformance,3.6,BPO,"Promotions / Appraisal, Salary & Benefits, Wor...",Paris,22.4,50k-1 Lakh,Teleperformance is the leading global provider...
13,Concentrix Corporation,3.9,BPO,"Job Security, Company Culture",Fremont,22.2,50k-1 Lakh,Concentrix is a technology-enabled global busi...
14,Jio,4.0,Telecom,"Job Security, Skill Development / Learning",Navi Mumbai,20.9,50k-1 Lakh,"Reliance Jio Infocomm Limited, a subsidiary of..."
15,Amazon,4.1,Internet,"Company Culture, Salary & Benefits, Work Life ...",Seattle,20.9,1 Lakh+,From an online bookstore to one of the world’s...
16,IBM,4.1,IT Services & Consulting,"Work Life Balance, Job Security, Skill Develop...",Armonk,20.0,1 Lakh+,"IBM aspires to make a lasting, positive impact..."
17,Reliance Retail,4.0,Retail,"Skill Development / Learning, Job Security",Navi Mumbai,19.1,1 Lakh+,"Reliance Retail is India's largest, fastest-gr..."
18,HDB Financial Services,4.0,NBFC,"Skill Development / Learning, Job Security, Co...",Ahmedabad,18.4,1 Lakh+,HDB Financial Services (HDBFS) is a leading No...
19,Larsen & Toubro Limited,4.1,Engineering & Construction,"Job Security, Skill Development / Learning",Mumbai,16.8,10k-50k,Larsen & Toubro is an Indian multinational eng...

# Generalization <br>
The website will not allow us to scrape buch of pages in one go, so we will scrap say 10 pages per cycle and merge the data frames. <br>
Change the argument of the range to scrap pages, I have provided an example here.

In [15]:
name = []
rating = []
reviews_K = []
highly_rated = []
ctype = []
hq = []
no_of_employees= []
desc = []
for j in range(2, 13):
  url = 'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
  headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
  webpage = requests.get(url, headers = headers).text

  soup = BeautifulSoup(webpage, 'lxml')
  companies = soup.find_all('div', class_ = "companyCardWrapper")

  for company in companies:
      name.append(company.find('h2').text.strip())
      rating.append(float(company.find('span', class_ = "companyCardWrapper__companyRatingValue").text.strip()))
      reviews_K.append(float(company.find('span', class_ ="companyCardWrapper__ActionCount").text.strip()[:-1]))

      try:
        highly_rated.append(company.find('span', class_ = "companyCardWrapper__ratingValues").text.strip())
      except:
        highly_rated.append(np.nan)

      hq.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[-1].split("+")[0])
      ctype.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[0])

      try:
        no_of_employees.append(company.find('span', class_="companyCardWrapper__interLinking").text.strip().split("|")[1][:-10])
      except:
         no_of_employees.append(np.nan)

      company_url = "https://www.ambitionbox.com/overview/{}-overview".format(company.find('h2').text.strip())
      webpage_desc = requests.get(company_url, headers = headers).text
      soup_desc = BeautifulSoup(webpage_desc, 'lxml')
      try:
        desc.append(soup_desc.find('div', class_="description mt-12").text)
      except:
        desc.append(np.nan)

Simply creating pandas data frame from list, by first converting to dictionary

In [16]:
dictionary ={'name': name, 'rating': rating, 'ctype': ctype, 'highly_rated': highly_rated, 'hq':hq,'reviews_K':reviews_K, 'no_of_employees': no_of_employees,'desc': desc}

df = pd.DataFrame(dictionary)

In [17]:
df = df[["name", "rating","ctype", "highly_rated","hq", "reviews_K", "no_of_employees",  "desc" ]]

In [18]:
df

,name,rating,ctype,highly_rated,hq,reviews_K,no_of_employees,desc
0,Vodafone Idea,4.2,Telecom,"Company Culture, Work Life Balance, Salary & B...",Mumbai,15.5,5k-10k,Vodafone Idea Limited is an Aditya Birla Group...
1,BYJU'S,3.1,EdTech,"Job Security, Work Life Balance, Company Culture",Bangalore,14.9,10k-50k,BYJU'S is the world's most valuable ed-tech co...
2,Kotak Mahindra Bank,3.9,Banking,Job Security,Mumbai,14.5,50k-1 Lakh,"In February 2003, Kotak Mahindra Finance Ltd. ..."
3,Deloitte,3.9,Management Consulting,"Job Security, Salary & Benefits, Skill Develop...",London,14.1,1 Lakh+,Deloitte is a leading global provider of audit...
4,Reliance Industries,4.1,Oil & Gas,"Job Security, Skill Development / Learning, Wo...",Navi Mumbai,13.9,1 Lakh+,NaN
...,...,...,...,...,...,...,...,...
215,Dabur,3.9,FMCG,Promotions / Appraisal,Ghaziabad,2.4,5k-10k,Dabur India Ltd. is one of India’s leading FMC...
216,Axis Direct,3.9,Financial Services,Promotions / Appraisal,San Mateo,2.4,1k-5k,We are a part of the lineage of Axis Group and...
217,JK Cement,4.2,Building Material,"Salary & Benefits, Company Culture, Job Security",Nimbahera,2.4,1k-5k,JK Cement Ltd. is one of India’s leading manuf...
218,Conduent,3.6,BPO,"Promotions / Appraisal, Salary & Benefits, Ski...",Florham Park,2.4,5k-10k,Conduent delivers digital business solutions a...
219,InterGlobe Aviation,3.6,Aviation,"Promotions / Appraisal, Salary & Benefits, Wor...",Gurgaon/Gurugram,2.4,10k-50k,IndiGo is India’s largest passenger airline wi...

Now, lets merge two data frame, from page 1 to page 12.

In [19]:
merge = [df_page_1, df]

In [20]:
updated = pd.concat(merge, ignore_index = True)

In [21]:
updated

,name,rating,ctype,highly_rated,hq,reviews_K,no_of_employees,desc
0,TCS,3.8,IT Services & Consulting,"Job Security, Work Life Balance",Mumbai,74.5,1 Lakh+,"Tata Consultancy Services is an IT services, c..."
1,Accenture,4.0,IT Services & Consulting,"Company Culture, Skill Development / Learning,...",Dublin,47.2,1 Lakh+,Accenture is a global professional services co...
2,Cognizant,3.9,IT Services & Consulting,Skill Development / Learning,Teaneck. New Jersey.,42.6,1 Lakh+,"At Cognizant, we give organizations the insigh..."
3,Wipro,3.8,IT Services & Consulting,Job Security,Bangalore/Bengaluru,40.1,1 Lakh+,"Wipro Limited (NYSE: WIT, BSE: 507685, NSE: WI..."
4,Capgemini,3.9,IT Services & Consulting,"Job Security, Work Life Balance, Skill Develop...",Paris,34.6,1 Lakh+,Capgemini is a global business and technology ...
...,...,...,...,...,...,...,...,...
235,Dabur,3.9,FMCG,Promotions / Appraisal,Ghaziabad,2.4,5k-10k,Dabur India Ltd. is one of India’s leading FMC...
236,Axis Direct,3.9,Financial Services,Promotions / Appraisal,San Mateo,2.4,1k-5k,We are a part of the lineage of Axis Group and...
237,JK Cement,4.2,Building Material,"Salary & Benefits, Company Culture, Job Security",Nimbahera,2.4,1k-5k,JK Cement Ltd. is one of India’s leading manuf...
238,Conduent,3.6,BPO,"Promotions / Appraisal, Salary & Benefits, Ski...",Florham Park,2.4,5k-10k,Conduent delivers digital business solutions a...
239,InterGlobe Aviation,3.6,Aviation,"Promotions / Appraisal, Salary & Benefits, Wor...",Gurgaon/Gurugram,2.4,10k-50k,IndiGo is India’s largest passenger airline wi...

we can save this data as a csv file.

In [22]:
updated.to_csv("Scrapped_data.csv")

#Thanks.